import React from 'react'

export default function Privacy() {
    return (
        <>
        {/* Privacy Section */}
        <section className="privacy-section">
                <div className="auto-container">
                    {/* Privacy Content */}
                    <div className="privacy-content">
                    <h2>Privacy Policy</h2>
                    <div className="date "><i>This Privacy Policy was last updated on November 3, 2020.</i></div>
                    
                    <h3>Introduction</h3> 
                    <p>At Codify College, our main priority is the well-being and education of our students and customers. It is of paramount importance to us that we do everything to ensure that our students receive the most effective course materials from our programs. One of the means of ensuring that our students get the information they need, in the most effective manner, is to view the visual journey that they take through our site. This, mixed with certain profile information, allows us to learn the in-site habits of our students. To do this, our website collects aggregate data and information from our website. As a result, we can offer a better user experience, better course materials, and better products.</p>
                    
                    <p>Below is Codify College’s  Privacy policy. To make this content more readable, we have broken it into sections as follows.</p>
                    
                    <h2>What Type of Information do we Collect?</h2>
                    <p>There are three types of information that Codify College collects.</p>

                   
                    <ul className="privacy-list">
                        <li>Collected information that is generated by our systems (or those of third parties) to track the traffic of our website. This allows us to tailor our marketing solutions.</li>
                        <li>Personal information such as; contact information (including, but not limited to, email) name, and occasionally billing details, financial and credit information (depending on whether you purchase a product through Codify College).</li>
                        <li>Information that is given to us through surveys, subscriptions, etc.</li>
                        
                    </ul>
                    <p>The type of information that Codify College collects depends on the type of services that you opt for on our website, on the phone, through sales and in-person at Open Evenings or Codify College external events.
                        In general, the information that we collect is not sensitive information. For example, we do not collect information regarding religion, sexual preference, race, or ethnic origin. Our purpose for collecting information is to provide you with a service or a product.
                        If it occurs that we require such information to supply a product to you, we will only request that information with your consent.</p>
                    </div>
                    {/* Privacy Content */}
                    <div className="privacy-content">
                    <h4>How we use aggregate data</h4>
                    <p>Codify College collects non-personal information as aggregate data like: how users utilize our website. For example, we monitor the number of visits to our site; we track the number of visits to certain pages on our site and the domain names of our users’ internet service provider.</p>
                    <p>This aggregate data allows us to examine trends and gather insights that would not be readable if the elements of data were viewed in isolation. It is a means that enables us to understand the workings of our website and services, and in turn, this allows us to improve and enhance our services. We may also use this data with our partners to improve our educational and employment services.</p>
                    
                    </div>
                    {/* Privacy Content */}
                    <div className="privacy-content">
                    <h4>IP (Internet Provider) Address</h4>
                    <p>Your IP address is supplied to Codify College through our web servers. This aids us in diagnosing problems or support issues with our servers.</p>

                    </div>
                    {/* Privacy Content */}
                    <div className="privacy-content">
                    <h4>Cookies</h4>
                    <p>Codify College uses cookies on our website. The use of cookies enables you to use services such as our training courses and challenges. It is possible for you to disable cookies. However, this may result in restricted access to some of our services and web pages.</p>
                    
                    </div>
                    {/* Privacy Content */}
                    <div className="privacy-content">
                    <h2>Means of collect information and data</h2>
                    <p>Codify College may collect data when you use our website, over the phone or through email.</p>
                    <p>Codify College  may use this data for any or a combination of these reasons:</p>
                    <ul className="privacy-list">
                        <li>To communicate with you (over phone, email, newsletters, etc.)</li>
                        <li> To facilitate and process contracts</li>
                        <li>To analyze the traffic on the Codify College website</li>
                        <li>To facilitate registration to our products/courses/bootcamps</li>
                        <li>To aid our marketing activities</li>
                        <li>To inform you of our courses/services/etc.</li>
                        <li>To pursue our legitimate interests reasonably in a manner that is reasonably expected as part of running our business. These</li>
                    </ul>
                    <p>interests do not materially impact your rights, freedom or interests. This includes registering for courses, challenges, events, and subscribing to our services, such as our newsletter. Information may also be collected when you use our student services or correspond with Codify College over the phone, through the website, via email or through any other forms of communication. Codify College may also collect data provided to us through our partners.</p>
                    </div>
                    {/* Privacy Content */}
                    <div className="privacy-content">
                    <h2>Disclosure of personal information to third parties</h2>
                    <p>On occasion, Codify College may disclose your information to our partners. This may facilitate enrollment or aid in the advances of our services. Our partners include training partners and employer partners. If you require a payment plan for any of our services, Codify College may collect personal information about you, such as; name, email, postal address and telephone number. Our billing partner will ask for financial and credit information. In this instance, Codify College does not see financial information. Our billing partner may require additional information to set up the plan. This is a matter for you and our payment plan partner and is not covered in this Privacy Statement, in that case we refer you to the Privacy Policy of the payment plan partner. If needed, Codify College may also disclose information to third party contractors who update the management and maintenance of our information systems. If this happens, Codify College takes any necessary steps to ensure that these contractors are bound by confidentiality agreements to protect your information. Apart from that outlined above, Codify College will not disclose your personal information without your permission – unless necessary by law or to prevent a threat to life or health.
                        </p>
                    </div>

                    <div className="privacy-content">
                    <h2>Klarna – privacy notice</h2>
                    <p>Codify College aims to offer a wide selection of payment methods. For this purpose, one of Codify College’s billing partners is <strong >Klarna</strong>.  To ensure accessibility for as many people as possible we offer the option to use <strong >Klarna</strong>‘s services to ensure flexible payments. In order to offer you <strong >Klarna</strong>’s payment methods, we might in the checkout pass your personal data in the form of contact and order details to <strong >Klarna</strong>, in order for <strong >Klarna</strong> to assess whether you qualify for their payment methods and to tailor those payment methods for you. However, regarding your financial and credit information disclosed specifically to <strong >Klarna</strong>, Codify College does not partake in any this information. Your personal data transferred is processed in line with <strong ><a className="text-danger"href="https://www.klarna.com/international/privacy-policy/">Klarna's' own privacy</a></strong> notice. Visit the embedded <a className="text-danger" href="https://www.klarna.com/international/privacy-policy/">link</a> to find out more about your specific regions Privacy Policy with <strong >Klarna</strong>.
                        </p>
                    </div>
                    
                       {/* Privacy Content */}
                       <div className="privacy-content">
                    <h2>Access to information about you</h2>
                    <p>If requested, Codify College will provide you with access to your personal information – unless there is an exception which applies under the General Data Protection Regulation, Data Protection Act 2018 and The Privacy and Electronic Communications – EC Directive – Regulations 2003. However, if we do deny access to data, we will explain to you why. In giving you access to the requested information, Codify College may recover any reasonable costs associated with the provision of information. If you would like to request information, please contact Codify College through the relevant means outlined at the bottom of this statement. If you are a registered Codify College user, access to your registered profile is available at any time.
                        </p>
                    </div>
                    <div className="privacy-content">
                        <h2>Updating information</h2>
                        <p>Codify College likes to ensure that the information we hold is accurate, correct and up to date. If the information we hold about you is inaccurate or out of date, or if you would like your details removed from our website, please contact  info@codifycollege.se. This will allow us to take reasonable steps to address or discuss alternative options with you.
                            </p>
                    </div>

                    <div className="privacy-content">
                        <h2>Security and storage of your information</h2>
                        <p>Codify College takes necessary and reasonable steps to ensure the protection and privacy of your personal information. In accordance with the Privacy Promise, we regularly review and implement new security and encryption technologies. While we do take all necessary steps to ensure the safety of your information, unfortunately, no data transmission over the internet can be guaranteed total security. While we do strive to protect all information, we can not ensure or warrant the security of any information you give to us or obtain from our online services and products. Therefore, the use of our services is at your own risk.
                        However, once your information does come into our possession – we take all reasonable actions to protect your information from unauthorized access, loss or misuse. We also strive to protect that information from modification or disclosure. If we find that a security breach has occurred, we have procedures to minimize the effects, and we will liaise with you and the office of the Data Protection Commissioner as appropriate.
                            </p>
                    </div>

                    <div className="privacy-content">
                        <h2>Additional information</h2>
                        <p><h5>Link to external sites</h5>
                            Codify College’s website does contain links to other websites for convenience purposes. While we may link to third party websites, it does in no way indicate an endorsement of their site, policies or practices – unless stated. If you are concerned about your privacy on those sites, please check their privacy policies.
                            </p>
                            
                        <p><h5>Elimination of personal information</h5>
                            Codify College’s website does contain links to other websites for convenience purposes. While we may link to third party websites, it does in no way indicate an endorsement of their site, policies or practices – unless stated. If you are concerned about your privacy on those sites, please check their privacy policies.
                            </p>
                            
                            <p><h5>Changes to our privacy policy</h5>
                            On occasion, Codify College may change its privacy policy. We advise our users to periodically review our policies. Continued use of our site and services constitutes your acceptance of the use and collection of your personal information.
                            For further information about your privacy rights you can contact Us with the contact details stated below.
                            </p>
                            </div>

                            <div className="privacy-content">
                        <h2>Questions regarding our Privacy Policy</h2>
                            <p>
                            We welcome questions and feedback regarding our website and our Privacy Policy. We may use said feedback to better our services, products, and websites. It may also be shared with our partners in aggregate form or with identifying characteristics removed.
                            If there are any questions regarding our Privacy Promise or any other angles of Codify College’s website, please contact us through any of the following means.
                            </p>
                            
                               <h5>Email: <p>info@codifycollege.se</p></h5> 
                                <h5>Phone: <p>+46723333899</p></h5> 
                                <h5>Registered Address:: <p>Röntgenvägen 1 141 52, Huddinge, Stockholm, Sweden</p></h5> 
                            </div>
                </div>
        </section>
        {/* End Privacy Section */}
</>
    )
}
